# =============================================================================
#  Secret — rabbitmq
#
#  !! ROTATE THESE VALUES IN PRODUCTION !!
# =============================================================================
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  labels:
    app.kubernetes.io/part-of: finance-app
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_DEFAULT_PASS: "guest"      # CHANGE_ME in prod
  RABBITMQ_URL:          "amqp://guest:guest@rabbitmq:5672"
