# =============================================================================
#  Namespace — dev  (created by the dev overlay before any other resource)
# =============================================================================
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    app.kubernetes.io/part-of: finance-app
    environment: dev
    kubernetes.io/metadata.name: dev
